milestone5 :Views
abdessalem1998/blog pull request #5
Opened 2022-04-15 07:39 UTC by abdessalem1998

In this pull request, I need to review my code for adding the Views associated with the Models and Controllers already created for the Blog app. in this part I did the following:

### Project requirements
- Implement the design from the sneak peek wireframes.
    - Styling is nice to have but focus on making sure everything functions first.
    
![All Users page wireframe](../images/blog_root_users.png) ![Single User page wireframe](../images/blog_user_page.png) ![All Posts by a given User page wireframe](../images/blog_user_all_posts.png) ![Single Post page wireframe](../images/blog_single_post.png)

- Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
- **Hint:** In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).

2022-04-15 08:44 UTC, julie-ify requested changes
## Hi @abdessalem1998,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Good code organization and working app ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

- [ ] **[REQUIRED]** Kindly add the title of the project and a brief description of the project in the README to make your README more descriptive and informative.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 08:44 UTC, julie-ify commented on app/views/users/show.html.erb
> +</section>
- [ ] On the users show page, each post should have the number of comments and likes under it as seen in the wireframe. Kindly add it.

<img width="299" alt="chrome_CC9a1vca3z" src="https://user-images.githubusercontent.com/81468675/163545489-f8ee6960-c3f3-4906-88be-9fee87f776be.png">

2022-04-15 08:44 UTC, julie-ify commented on app/views/posts/index.html.erb
> +</section>
- [ ] On the post index page, each post should have the number of comments and likes under it as seen in the wireframe. Kindly add it.

<img width="274" alt="chrome_sU3KuUIl63" src="https://user-images.githubusercontent.com/81468675/163546537-7e07a623-8527-4b8f-ac47-b2bf2a9bd5e4.png">

2022-04-15 08:44 UTC, julie-ify commented on app/views/posts/show.html.erb
> +</section>
- [ ] Kindly make this post show page to match the wireframe. As seen in the wireframe, the post author's name is at the top of the post beside the post title but yours is at the end. Kindly fix this
- [ ] Also add the number of comments and likes for the post as seen in the wireframe.

<img width="271" alt="chrome_eRPLqB9GVS" src="https://user-images.githubusercontent.com/81468675/163547361-86ad2f8f-d8e8-4a78-83ec-3520aba3d71d.png">

2022-05-04 13:54 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @abdessalem1998,  

Your project is complete! 

## Good Points 👍 
- All pages are styled based on provided wireframe ✔️ 
- 3 recent posts and 5 recent comments functions are working ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 08:59 UTC, merged